/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package petshop.gui;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
/**
 *
 * @author Paulo Guilherme
 */
public class BaseGUINetBeans extends javax.swing.JFrame {
    protected static final Color COR_PRIMARIA = new Color(70, 130, 180);
    protected static final Color COR_SECUNDARIA = new Color(240, 248, 255);
    protected static final Font FONTE_TITULO = new Font("Arial", Font.BOLD, 16);
    protected static final Font FONTE_PADRAO = new Font("Arial", Font.PLAIN, 12);
    /**
     * Creates new form BaseGUINetBeans
     */
    public BaseGUINetBeans() {
        configurarJanela();
        initComponents();
    }

    public BaseGUINetBeans(String titulo) {
        super(titulo);
        configurarJanela();
        initComponents();
    }

    private void configurarJanela() {
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new BorderLayout());
        getContentPane().setBackground(COR_SECUNDARIA);
        setLocationRelativeTo(null);
    }

    protected void aplicarEstiloBotao(JButton botao) {
        botao.setFont(FONTE_PADRAO);
        botao.setBackground(COR_PRIMARIA);
        botao.setForeground(Color.WHITE);
        botao.setFocusPainted(false);
        botao.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
    }

    protected JPanel criarPainelComTitulo(String titulo) {
        JPanel painel = new JPanel(new BorderLayout());
        painel.setBackground(COR_SECUNDARIA);
        painel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        
        JLabel labelTitulo = new JLabel(titulo, JLabel.CENTER);
        labelTitulo.setForeground(COR_PRIMARIA);
        painel.add(labelTitulo, BorderLayout.NORTH);
        
        return painel;
    }

    protected void aplicarEstiloPainel(JPanel painel) {
        painel.setBackground(COR_SECUNDARIA);
    }

    protected void aplicarEstiloTitulo(JLabel label) {
        label.setFont(FONTE_TITULO);
        label.setForeground(COR_PRIMARIA);
        label.setHorizontalAlignment(SwingConstants.CENTER);
    }

    protected JButton criarBotao(String texto, ActionListener action) {
        JButton botao = new JButton(texto);
        botao.setBackground(COR_PRIMARIA);
        botao.setForeground(Color.WHITE);
        botao.setFocusPainted(false);
        botao.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        if (action != null) {
            botao.addActionListener(action);
        }
        return botao;
    }
    
    protected void mostrarMensagem(String mensagem) {
        JOptionPane.showMessageDialog(this, mensagem, "Informação", JOptionPane.INFORMATION_MESSAGE);
    }
    
    protected void mostrarErro(String erro) {
        JOptionPane.showMessageDialog(this, erro, "Erro", JOptionPane.ERROR_MESSAGE);
    }
    
    protected boolean confirmarAcao(String mensagem) {
        int resposta = JOptionPane.showConfirmDialog(
            this, mensagem, "Confirmação",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE
        );
        return resposta == JOptionPane.YES_OPTION;
    }

    protected void configurarComponentes() {
        // Implementação nas classes filhas
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaseGUINetBeans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaseGUINetBeans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaseGUINetBeans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaseGUINetBeans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaseGUINetBeans().setVisible(true);
            }
        });
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
