/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package petshop.gui;

import javax.swing.JOptionPane;

import petshop.model.Animal;
import petshop.model.Atendimento;
import petshop.model.Cliente;
import petshop.model.Funcionario;
import petshop.repository.AnimalRepository;
import petshop.repository.AtendimentoRepository;
import petshop.repository.ClienteRepository;
import petshop.repository.FuncionarioRepository;
import petshop.service.*;
import petshop.util.ValidadorEntrada;

/**
 *
 * @author paulo_schnaufer
 */
public class MenuServicesGUI extends BaseGUINetBeans {

    private Service service;
    private MenuPrincipalGUI menuAnterior;
    private String tipoEntidade;

    // Repositórios (vindos do menu principal)
    private ClienteRepository clienteRepository;
    private FuncionarioRepository funcionarioRepository;
    private AnimalRepository animalRepository;
    private AtendimentoRepository atendimentoRepository;

    /**
     * Creates new form MenuServicesGUIPanel
     */
    public MenuServicesGUI(MenuPrincipalGUI menuAnterior, Service service, String tipoEntidade) {
        this.menuAnterior = menuAnterior;
        this.service = service;
        this.tipoEntidade = tipoEntidade;
        
        trazRepositorios();
        
        initComponents();
        configurarTela();
    }

    private void trazRepositorios() {
        if (service instanceof ClienteService) {
            this.clienteRepository = ((ClienteService) service).getRepository();
        } else if (service instanceof FuncionarioSerivce) {
            this.funcionarioRepository = ((FuncionarioService) service).getRepository();
        } else if (service instanceof AnimalService) {
            this.animalRepository = ((AnimalService) service).getAnimalRepository();
            this.clienteRepository = ((AnimalService) service).getClienteRepository();
        } else if (service instanceof AtendimentoService) {
            this.clienteRepository = ((AtendimentoService) service).getClienteRepository();
            this.funcionarioRepository = ((AtendimentoService) service).getFuncionarioRepository();
            this.animalRepository = ((AtendimentoService) service).getAnimalRepoository();
            this.atendimentoRepository = ((AtendimentoService) service).getAtendimentoRepository();
        }
    }

    private void configurarTela() {
        setTitle("Petsistema — " + tipoEntidade);
        tituloLbl.setText("Menu " + tipoEntidade);
        
        voltarBtn.addActionListener(e -> voltarMenuPrincipal());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alterarBtn = new javax.swing.JButton();
        consultarBtn = new javax.swing.JButton();
        cadastrarBtn = new javax.swing.JButton();
        removerBtn = new javax.swing.JButton();
        relatorioBtn = new javax.swing.JButton();
        tituloLbl = new javax.swing.JLabel();
        voltarBtn = new javax.swing.JButton();

        alterarBtn.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        alterarBtn.setText("Alterar");
        alterarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alterarBtnMouseClicked(evt);
            }
        });

        consultarBtn.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        consultarBtn.setText("Consultar");
        consultarBtn.setAlignmentY(0.0F);
        consultarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultarBtnMouseClicked(evt);
            }
        });

        cadastrarBtn.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        cadastrarBtn.setText("Cadastrar");
        cadastrarBtn.setAlignmentY(0.0F);
        cadastrarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cadastrarBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cadastrarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarBtnMouseClicked(evt);
            }
        });
        cadastrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarBtnActionPerformed(evt);
            }
        });

        removerBtn.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        removerBtn.setText("Remover");
        removerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removerBtnMouseClicked(evt);
            }
        });

        relatorioBtn.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        relatorioBtn.setText("Relatório");

        tituloLbl.setFont(new java.awt.Font("Bodoni MT Black", 0, 36)); // NOI18N
        tituloLbl.setText("Petsistema");

        voltarBtn.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        voltarBtn.setText("Voltar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cadastrarBtn)
                    .addComponent(consultarBtn)
                    .addComponent(alterarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(relatorioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloLbl))
                .addGap(130, 130, 130))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(voltarBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(tituloLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastrarBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(consultarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(alterarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(removerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(relatorioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(voltarBtn)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void alterarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alterarBtnMouseClicked
        try {
            if (service instanceof ClienteService) {
                alterarClienteGUI();
            } else if (service instanceof FuncionarioService) {
                alterarFuncionarioGUI();
            } else if (service instanceof AnimalService) {
                alterarAnimalGUI();
            } else if (service instanceof AtendimentoService) {
                alterarAtendimentoGUI();
            }
        } catch (Exception e) {
            mostrarErro("Erro ao alterar: " + e.getMessage());
        }
    }//GEN-LAST:event_alterarBtnMouseClicked

    private void consultarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultarBtnMouseClicked
        try {
            if (service instanceof ClienteService) {
                consultarClienteGUI();
            } else if (service instanceof FuncionarioService) {
                consultarFuncionarioGUI();
            } else if (service instanceof AnimalService) {
                consultarAnimalGUI();
            } else if (service instanceof AtendimentoService) {
                consultarAtendimentoGUI();
            }
        } catch (Exception e) {
            mostrarErro("Erro ao consultar: " + e.getMessage());
        }
    }//GEN-LAST:event_consultarBtnMouseClicked

    private void cadastrarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarBtnMouseClicked
        try {
            if (service instanceof ClienteService) {
                cadastrarClienteGUI();
            } else if (service instanceof FuncionarioService) {
                cadastrarFuncionarioGUI();
            } else if (service instanceof AnimalService) {
                cadastrarAnimalGUI();
            } else if (service instanceof AtendimentoService) {
                cadastrarAtendimentoGUI();
            }
        } catch (Exception e) {
            mostrarErro("Erro ao cadastrar: " + e.getMessage());
        }
    }//GEN-LAST:event_cadastrarBtnMouseClicked

    private void cadastrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarBtnActionPerformed

    private void removerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removerBtnMouseClicked
        try {
            if (service instanceof ClienteService) {
                removerClienteGUI();
            } else if (service instanceof FuncionarioService) {
                removerFuncionarioGUI();
            } else if (service instanceof AnimalService) {
                removerAnimalGUI();
            } else if (service instanceof AtendimentoService) {
                removerAtendimentoGUI();
            }
        } catch (Exception e) {
            mostrarErro("Erro ao remover: " + e.getMessage());
        }
    }//GEN-LAST:event_removerBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarBtn;
    private javax.swing.JButton cadastrarBtn;
    private javax.swing.JButton consultarBtn;
    private javax.swing.JButton relatorioBtn;
    private javax.swing.JButton removerBtn;
    private javax.swing.JLabel tituloLbl;
    private javax.swing.JButton voltarBtn;
    // End of variables declaration//GEN-END:variables
}
