/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package petshop.gui;

/**
 *
 * @author Paulo Guilherme
 */
public class MenuServicesGUI extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipalGUI
     */
    public MenuServicesGUI() {
        initComponents();
    }

    private void cadastrarClienteGUI() {
        Cliente cliente = new Cliente(nome, telefone, email, rg, cpf);
        clienteRepository.save(cpf, cliente);
        mostrarMensagem("Cliente cadastrado com sucesso");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alterarBtn = new javax.swing.JButton();
        consultarBtn = new javax.swing.JButton();
        cadastrarBtn = new javax.swing.JButton();
        removerBtn = new javax.swing.JButton();
        tituloLbl = new javax.swing.JLabel();
        relatorioBtn = new javax.swing.JButton();
        voltarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Petsistema");

        alterarBtn.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        alterarBtn.setText("Alterar");
        alterarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alterarBtnMouseClicked(evt);
            }
        });

        consultarBtn.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        consultarBtn.setText("Consultar");
        consultarBtn.setAlignmentY(0.0F);
        consultarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultarBtnMouseClicked(evt);
            }
        });

        cadastrarBtn.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        cadastrarBtn.setText("Cadastrar");
        cadastrarBtn.setAlignmentY(0.0F);
        cadastrarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cadastrarBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cadastrarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarBtnMouseClicked(evt);
            }
        });
        cadastrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarBtnActionPerformed(evt);
            }
        });

        removerBtn.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        removerBtn.setText("Remover");
        removerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removerBtnMouseClicked(evt);
            }
        });

        tituloLbl.setFont(new java.awt.Font("Bodoni MT Black", 0, 36)); // NOI18N
        tituloLbl.setText("Petsistema");

        relatorioBtn.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        relatorioBtn.setText("Relatório");

        voltarBtn.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        voltarBtn.setText("Voltar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(voltarBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(tituloLbl)))
                .addGap(129, 132, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cadastrarBtn)
                    .addComponent(consultarBtn)
                    .addComponent(alterarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(relatorioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(181, 181, 181))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(tituloLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(cadastrarBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(consultarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(alterarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(removerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(relatorioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(voltarBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarBtnMouseClicked
        try {
            if (service instanceof ClienteService) {
                cadastrarClienteGUI();
            }
        } catch (Exception e) {
            mostrarErro("Erro ao cadastrar: " + e.getMessage());
        }
    }//GEN-LAST:event_cadastrarBtnMouseClicked

    private void consultarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultarBtnMouseClicked
        MenuFuncionarioGUI menuFuncionario = new MenuFuncionarioGUI(this, funcionarioService);
        menuFuncionario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_consultarBtnMouseClicked

    private void alterarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alterarBtnMouseClicked
        MenuAnimalGUI menuAnimal = new MenuAnimalGUI(this, animalService);
        menuAnimal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_alterarBtnMouseClicked

    private void removerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removerBtnMouseClicked
        MenuAtendimentoGUI menuAtendimento = new MenuAtendimentoGUI(this, atendimentoService);
        menuAtendimento.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_removerBtnMouseClicked

    private void cadastrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuServicesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuServicesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuServicesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuServicesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuServicesGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarBtn;
    private javax.swing.JButton cadastrarBtn;
    private javax.swing.JButton consultarBtn;
    private javax.swing.JButton relatorioBtn;
    private javax.swing.JButton removerBtn;
    private javax.swing.JLabel tituloLbl;
    private javax.swing.JButton voltarBtn;
    // End of variables declaration//GEN-END:variables
}
